- Dockerfile
> Revert "update Dockerfile to support building protobufs against python3"

- keepkey/local/baremetal/ethereum.c
This is completely untested. I didn't see any existing examples of how to write
a testcase (not that I'm able to actually run anything yet at this point in my
"build it with clang" adventure). That being said, it does build for me.
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md
It'd be a good idea to try out the example testcases in the EIP before merging
this, but I'm not sure how to do that without being able to run the code. I
should get there eventually...
As with all of my commits lately: please test this before merging. I can't, so you should.
> Implement EIP55

- keepkey/local/baremetal/ethereum.c
Reverts keepkey/keepkey-firmware#29
> Revert "Implement EIP55"

- README.md
- docs/Coins.md
- docs/README.md
Trezor provide great docs for this: https://github.com/trezor/trezor-core/blob/master/docs/coins/README.md we should too.
> Document our derivation paths

- lib/firmware/signing.c
This allows treating BIP44+BIP49+BIP84 paths with the same account
number & coin type as one big account.
> Make UTXO signing more permissive w.r.t. segwit change

- include/keepkey/board/layout.h
- include/keepkey/firmware/coins.h
- lib/board/layout.c
- lib/firmware/app_confirm.c
- lib/firmware/coins.c
- lib/firmware/ethereum.c
- lib/firmware/exchange.c
- unittests/firmware/coins.cpp
> Bugfix: Fuzzy ExchangeType validation

- .circleci/config.yml
... so we can use it in python-keepkey, and keepkey.js for CI
> Push latest successful as kktech/kkemu:$BRANCH_NAME

- lib/firmware/ethereum.c
https://github.com/trezor/trezor-mcu/commit/fd46339f5cc2971cd202697503c81a04d4b402f3
> ethereum: clear local variables in layoutEthereumFee

- include/keepkey/board/memory.h
- include/keepkey/board/util.h
- lib/board/usb.c
- lib/board/util.c
- lib/firmware/app_confirm.c
- tools/bootloader/main.c
- tools/firmware/keepkey_main.c
> webusb-friendly labelling

- include/keepkey/firmware/app_confirm.h
- lib/firmware/app_confirm.c
- lib/firmware/transaction.c
https://github.com/trezor/trezor-mcu/commit/9cd261c81a1b94cead04af6d09c68284d0e37851
> layout: parse and show OMNI transactions

- lib/firmware/ethereum.c
The amount doesn't actually include the fee... fee is extra.
> ethereum: clarify fee messaging

- include/keepkey/firmware/coins.h
- include/keepkey/firmware/eos-contracts/eosio.system.h
- lib/firmware/coins.c
- lib/firmware/eos-contracts/eosio.system.c
- unittests/firmware/coins.cpp
https://github.com/trezor/trezor-firmware/issues/168#issuecomment-495262620
> EOS: to maximize compatibilty, remove slip48, and go with ledger paths

- unittests/firmware/nano.cpp
Should fix some problems @BitHighlander ran into when building on linux.
> Fix the unittest build on non-clang hosts

- lib/firmware/CMakeLists.txt
... since ethereum_tokens.py already does the hashing & diffing
> build: better version of 19356442

- lib/firmware/fsm_msg_cosmos.h
> firmware: fix cosmos show address

- CMakeLists.txt
- Dockerfile
- cmake/caches/docker.cmake
- docs/Build.md
- include/pb.h
- include/pb_common.h
- include/pb_decode.h
- include/pb_encode.h
- lib/firmware/fsm_msg_ethereum.h
- lib/transport/CMakeLists.txt
- lib/transport/pb_common.c
- lib/transport/pb_decode.c
- lib/transport/pb_encode.c
- scripts/build/docker/device/debug.sh
- scripts/build/docker/device/release.sh
- scripts/build/docker/emulator/debug.sh
- scripts/emulator/Dockerfile
- scripts/emulator/python-keepkey.Dockerfile
> Update nanopb to v0.3.9.4

- README.md
> firmware: fix build reproducibility

- include/keepkey/board/pubkeys.h
- include/keepkey/transport/messages-tendermint.options
- lib/board/confirm_sm.c
- lib/firmware/coins.c
- lib/firmware/crypto.c
- lib/firmware/ethereum_tokens.c
- lib/firmware/fsm_msg_common.h
- lib/firmware/fsm_msg_tendermint.h
- lib/firmware/fsm_msg_thorchain.h
- lib/firmware/signtx_tendermint.c
- lib/firmware/storage.c
- lib/firmware/thorchain.c
- tools/firmware/keepkey_main.c
(This is the same as #278, except for 7d6bfe0, bcab1c3, and as otherwise noted.)
> some fixes for #278

- .github/CODEOWNERS
- include/keepkey/board/confirm_sm.h
- lib/firmware/signing.c
Added some generalized debugging code as well as utxo stage debugging switch only available in debug mode.
Fixed code owners.
> Utxo sign debug

- tools/firmware/keepkey_main.c
> chore: rename a confusing function

- scripts/emulator/bridge.py
Reverts keepkey/keepkey-firmware#306
> Revert "emulator: expose unchunked transport"

- CMakeLists.txt
- lib/firmware/ethereum.c
- lib/firmware/fsm_msg_osmosis.h
* adds op, bnb, xdai, matic chain support
* fix denomination on osmosis confirmation screens
* removes support for deprecated testnets
> add op, bnb, matic, xdai chain support
